import type { AdvancedRequisition } from "./requisition-types";

export const advancedRequisitions: AdvancedRequisition[] = [
  {
    id: "CS-001",
    raisedByName: "Priya Sharma",
    raisedByPhone: "+91 98765 43210",
    flow: "studio",
    salesData: undefined,
    hiringData: {
      clientName: "Razorpay",
      dealId: "DEAL-001",
      dealType: "Retainer",
      studioType: "Hybrid",
      geography: "India",
      talentType: "",
      opportunityStage: "SLA signed & contraction is on the platform",
      clientDetails: "Leading fintech payments company. Scale: 500+ articles/year. Expectations: High-quality fintech content with deep domain knowledge. Complexity: High regulatory sensitivity.",
      clientPay: 176000,
      mrr: 176000,
      contractDuration: "12 months",
      targetMarginPercent: 40,
      lineItems: [
        {
          id: "li-1", creatorType: "Writer", otherCreatorTypeSpec: "", numberOfCreators: 3, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "40,000 words", estimatedHoursPerMonth: "",
          unitPrice: 3.5, targetUnitMargin: 40, isCombinedPay: false,
          grossMargin: 56000, grossMarginPercent: 40,
          domainExpertise: "Fintech, Payments, Banking", languageRequirement: "English",
          toolsRequired: "Google Docs, Grammarly", portfolioExpectation: "Published fintech articles",
          turnaroundTime: "48 hours per article", replacementRisk: "Medium",
        },
        {
          id: "li-2", creatorType: "Editor", otherCreatorTypeSpec: "", numberOfCreators: 1, experienceLevel: "Mid (2–5 yrs)",
          paymentModel: "Monthly Retainer", estimatedMonthlyOutput: "", estimatedHoursPerMonth: "80",
          unitPrice: 0, targetUnitMargin: 40, isCombinedPay: false,
          grossMargin: 15000, grossMarginPercent: 41.7,
          domainExpertise: "Fintech, SaaS", languageRequirement: "English",
          toolsRequired: "Google Docs, CMS", portfolioExpectation: "Editing portfolio",
          turnaroundTime: "24 hours turnaround", replacementRisk: "Low",
        },
      ],
      urgencyScale: 5,
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "In progress",
    rmgNotes: "Approved. Good margins. Prioritize experienced fintech writers.",
    rejectionReason: "",
    podLeadAssigned: "Neha Gupta",
    recruiterAssigned: "Ravi Kumar",
    linkedInRecruiterLink: "https://www.linkedin.com/recruiter/projects/12345",
    atsSheetLink: "",
    targetClosureDate: "2026-02-28",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-20T14:30:00Z",
    totalClientRevenue: 176000,
    totalCreatorCost: 105000,
    grossMargin: 71000,
    grossMarginPercent: 40.3,
    targetMarginPercent: 40,
    dailyUpdates: [
      { id: "du-1", date: "2026-02-20", recruiterName: "Ravi Kumar", profilesIdentified: 12, profilesContacted: 8, profilesScreened: 5, profilesShared: 3, interviewsScheduled: 2, offersRolledOut: 0, selected: 0, dropOffs: 1, blockers: "Fintech writers in short supply", notes: "Good pipeline building" },
      { id: "du-2", date: "2026-02-21", recruiterName: "Ravi Kumar", profilesIdentified: 8, profilesContacted: 6, profilesScreened: 4, profilesShared: 2, interviewsScheduled: 1, offersRolledOut: 1, selected: 0, dropOffs: 0, blockers: "", notes: "One strong candidate in final round" },
    ],
    auditLog: [
      { id: "a-1", fieldChanged: "status", oldValue: "Approved but not assigned", newValue: "In progress", editedBy: "System", timestamp: "2026-02-15T10:00:00Z" },
    ],
  },
  {
    id: "S-001",
    raisedByName: "Arjun Mehta",
    raisedByPhone: "+91 99887 76655",
    flow: "sales",
    salesData: {
      clientName: "Stripe",
      opportunityName: "Stripe India Content Launch",
      dealType: "Pilot",
      resourceType: "Freelancer(s)",
      specificResourceTypes: ["Writer", "Designer"],
      otherResourceTypeSpec: "",
      expectedCreatorPay: "₹5-7 per word, ₹4500 per design",
      expectedClientBilling: "₹3,20,000",
      expectedMarginPercent: 38,
      opportunityStage: "Proposal",
      urgency: "high",
    },
    hiringData: undefined,
    status: "RMG approval Pending",
    rmgNotes: "",
    rejectionReason: "",
    podLeadAssigned: "",
    recruiterAssigned: "",
    linkedInRecruiterLink: "",
    atsSheetLink: "",
    targetClosureDate: "",
    createdAt: "2026-02-22T09:00:00Z",
    updatedAt: "2026-02-22T09:00:00Z",
    totalClientRevenue: 320000,
    totalCreatorCost: 198400,
    grossMargin: 121600,
    grossMarginPercent: 38,
    targetMarginPercent: 38,
    dailyUpdates: [],
    auditLog: [],
  },
  {
    id: "F-001",
    raisedByName: "Vikram Singh",
    raisedByPhone: "+91 88776 55443",
    flow: "freelancer",
    salesData: undefined,
    hiringData: {
      clientName: "Freshworks",
      dealId: "DEAL-003",
      dealType: "Retainer",
      studioType: "",
      geography: "",
      talentType: "India-based talent for Global clients",
      opportunityStage: "SLA signed & contraction is on the platform",
      clientDetails: "Enterprise SaaS company. Scale: 200+ pieces/quarter. Expectations: Technical depth, SEO-optimized. Complexity: Multiple product lines.",
      clientPay: 315000,
      mrr: 315000,
      contractDuration: "6 months",
      targetMarginPercent: 40,
      lineItems: [
        {
          id: "li-3", creatorType: "Writer", otherCreatorTypeSpec: "", numberOfCreators: 2, experienceLevel: "Expert (8+ yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "30,000 words", estimatedHoursPerMonth: "",
          unitPrice: 5.8, targetUnitMargin: 40, isCombinedPay: false,
          grossMargin: 70000, grossMarginPercent: 40,
          domainExpertise: "SaaS, Customer Success", languageRequirement: "English (Native)",
          toolsRequired: "Google Docs, Notion", portfolioExpectation: "SaaS case studies",
          turnaroundTime: "5 business days", replacementRisk: "High",
        },
        {
          id: "li-4", creatorType: "Designer", otherCreatorTypeSpec: "", numberOfCreators: 1, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Assignment", estimatedMonthlyOutput: "15 designs", estimatedHoursPerMonth: "60",
          unitPrice: 5500, targetUnitMargin: 40, isCombinedPay: false,
          grossMargin: 57500, grossMarginPercent: 41.1,
          domainExpertise: "SaaS, Enterprise", languageRequirement: "English",
          toolsRequired: "Figma, Illustrator", portfolioExpectation: "B2B SaaS design portfolio",
          turnaroundTime: "3 business days", replacementRisk: "Medium",
        },
      ],
      urgencyScale: 3,
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "Closed – allotted",
    rmgNotes: "Good deal. Approved.",
    rejectionReason: "",
    podLeadAssigned: "Neha Gupta",
    recruiterAssigned: "Neha Gupta",
    linkedInRecruiterLink: "https://www.linkedin.com/recruiter/projects/67890",
    atsSheetLink: "https://docs.google.com/spreadsheets/d/xyz",
    targetClosureDate: "2026-02-10",
    createdAt: "2026-01-05T11:00:00Z",
    updatedAt: "2026-02-10T16:00:00Z",
    totalClientRevenue: 315000,
    totalCreatorCost: 187500,
    grossMargin: 127500,
    grossMarginPercent: 40.5,
    targetMarginPercent: 40,
    dailyUpdates: [],
    auditLog: [],
  },
  {
    id: "F-002",
    raisedByName: "Priya Sharma",
    raisedByPhone: "+91 98765 43210",
    flow: "freelancer",
    salesData: undefined,
    hiringData: {
      clientName: "Zerodha",
      dealId: "DEAL-004",
      dealType: "Retainer",
      studioType: "",
      geography: "",
      talentType: "India-based talent for Indian clients",
      opportunityStage: "SLA back-and-forth",
      clientDetails: "Leading discount brokerage. Scale: Large volume of educational content. Expectations: SEBI-compliant, investor-friendly. Complexity: Regulatory constraints.",
      clientPay: 280000,
      mrr: 280000,
      contractDuration: "12 months",
      targetMarginPercent: 45,
      lineItems: [
        {
          id: "li-5", creatorType: "Writer", otherCreatorTypeSpec: "", numberOfCreators: 4, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "60,000 words", estimatedHoursPerMonth: "",
          unitPrice: 4.7, targetUnitMargin: 45, isCombinedPay: false,
          grossMargin: 112000, grossMarginPercent: 40,
          domainExpertise: "Finance, Investments", languageRequirement: "English, Hindi",
          toolsRequired: "Google Docs", portfolioExpectation: "Finance writing samples",
          turnaroundTime: "72 hours", replacementRisk: "High",
        },
      ],
      urgencyScale: 5,
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "Approved but not assigned",
    rmgNotes: "Margin below target at line level. Need to renegotiate writer pay or increase client billing.",
    rejectionReason: "",
    podLeadAssigned: "",
    recruiterAssigned: "",
    linkedInRecruiterLink: "",
    atsSheetLink: "",
    targetClosureDate: "",
    createdAt: "2026-02-05T08:00:00Z",
    updatedAt: "2026-02-23T10:00:00Z",
    totalClientRevenue: 280000,
    totalCreatorCost: 168000,
    grossMargin: 112000,
    grossMarginPercent: 40,
    targetMarginPercent: 45,
    dailyUpdates: [],
    auditLog: [
      { id: "a-2", fieldChanged: "status", oldValue: "RMG approval Pending", newValue: "Approved but not assigned", editedBy: "RMG", timestamp: "2026-02-23T10:00:00Z" },
    ],
  },
];
