import type { AdvancedRequisition } from "./requisition-types";

export const advancedRequisitions: AdvancedRequisition[] = [
  {
    id: "AREQ-001",
    raisedByName: "Priya Sharma",
    raisedByPhone: "+91 98765 43210",
    department: "VSD",
    flow: "vsd",
    salesData: undefined,
    vsdData: {
      clientName: "Razorpay",
      dealId: "DEAL-001",
      dealType: "Retainer",
      studioType: "Dedicated",
      geography: "India",
      opportunityStage: "SLA signed & contraction is on the platform",
      clientDetails: "Leading fintech payments company. Scale: 500+ articles/year. Expectations: High-quality fintech content with deep domain knowledge. Complexity: High regulatory sensitivity.",
      lineItems: [
        {
          id: "li-1", creatorTypes: ["Writer"], numberOfCreators: 3, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "40,000 words", estimatedHoursPerMonth: "",
          clientPay: 140000, creatorPay: 84000, isCombinedPay: false, targetMarginPercent: 40,
          grossMargin: 56000, grossMarginPercent: 40,
          domainExpertise: "Fintech, Payments, Banking", languageRequirement: "English",
          toolsRequired: "Google Docs, Grammarly", portfolioExpectation: "Published fintech articles",
          turnaroundTime: "48 hours per article", replacementRisk: "Medium",
        },
        {
          id: "li-2", creatorTypes: ["Editor"], numberOfCreators: 1, experienceLevel: "Mid (2–5 yrs)",
          paymentModel: "Monthly Retainer", estimatedMonthlyOutput: "", estimatedHoursPerMonth: "80",
          clientPay: 36000, creatorPay: 21000, isCombinedPay: false, targetMarginPercent: 40,
          grossMargin: 15000, grossMarginPercent: 41.7,
          domainExpertise: "Fintech, SaaS", languageRequirement: "English",
          toolsRequired: "Google Docs, CMS", portfolioExpectation: "Editing portfolio",
          turnaroundTime: "24 hours turnaround", replacementRisk: "Low",
        },
      ],
      requiredStartDate: "2026-01-15",
      deadlineToClose: "2026-02-28",
      urgency: "medium",
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "In Progress",
    headOfSupplyNotes: "Approved. Good margins. Prioritize experienced fintech writers.",
    rejectionReason: "",
    taManagerAssigned: "Neha Gupta",
    recruiterAssigned: "Ravi Kumar",
    linkedInRecruiterLink: "https://www.linkedin.com/recruiter/projects/12345",
    targetClosureDate: "2026-02-28",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-02-20T14:30:00Z",
    totalClientRevenue: 176000,
    totalCreatorCost: 105000,
    grossMargin: 71000,
    grossMarginPercent: 40.3,
    targetMarginPercent: 40,
    dailyUpdates: [
      { id: "du-1", date: "2026-02-20", recruiterName: "Ravi Kumar", profilesIdentified: 12, profilesContacted: 8, profilesScreened: 5, profilesShared: 3, interviewsScheduled: 2, offersRolledOut: 0, selected: 0, dropOffs: 1, blockers: "Fintech writers in short supply", notes: "Good pipeline building" },
      { id: "du-2", date: "2026-02-21", recruiterName: "Ravi Kumar", profilesIdentified: 8, profilesContacted: 6, profilesScreened: 4, profilesShared: 2, interviewsScheduled: 1, offersRolledOut: 1, selected: 0, dropOffs: 0, blockers: "", notes: "One strong candidate in final round" },
    ],
    auditLog: [
      { id: "a-1", fieldChanged: "status", oldValue: "Approved – Assigning", newValue: "In Progress", editedBy: "System", timestamp: "2026-02-15T10:00:00Z" },
    ],
  },
  {
    id: "AREQ-002",
    raisedByName: "Arjun Mehta",
    raisedByPhone: "+91 99887 76655",
    department: "Sales",
    flow: "sales",
    salesData: {
      clientName: "Stripe",
      opportunityName: "Stripe India Content Launch",
      dealType: "Pilot",
      resourceType: "Freelancer(s)",
      specificResourceTypes: ["Writer", "Designer"],
      expectedCreatorPay: "₹5-7 per word, ₹4500 per design",
      expectedClientBilling: "₹3,20,000",
      expectedMarginPercent: 38,
      opportunityStage: "Proposal",
      urgency: "high",
    },
    vsdData: undefined,
    status: "Pending Head of Supply Review",
    headOfSupplyNotes: "",
    rejectionReason: "",
    taManagerAssigned: "",
    recruiterAssigned: "",
    linkedInRecruiterLink: "",
    targetClosureDate: "",
    createdAt: "2026-02-22T09:00:00Z",
    updatedAt: "2026-02-22T09:00:00Z",
    totalClientRevenue: 320000,
    totalCreatorCost: 198400,
    grossMargin: 121600,
    grossMarginPercent: 38,
    targetMarginPercent: 38,
    dailyUpdates: [],
    auditLog: [],
  },
  {
    id: "AREQ-003",
    raisedByName: "Vikram Singh",
    raisedByPhone: "+91 88776 55443",
    department: "Account Management",
    flow: "vsd",
    salesData: undefined,
    vsdData: {
      clientName: "Freshworks",
      dealId: "DEAL-003",
      dealType: "Retainer",
      studioType: "Dedicated",
      geography: "US",
      opportunityStage: "SLA signed & contraction is on the platform",
      clientDetails: "Enterprise SaaS company. Scale: 200+ pieces/quarter. Expectations: Technical depth, SEO-optimized. Complexity: Multiple product lines.",
      lineItems: [
        {
          id: "li-3", creatorTypes: ["Writer"], numberOfCreators: 2, experienceLevel: "Expert (8+ yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "30,000 words", estimatedHoursPerMonth: "",
          clientPay: 175000, creatorPay: 105000, isCombinedPay: false, targetMarginPercent: 40,
          grossMargin: 70000, grossMarginPercent: 40,
          domainExpertise: "SaaS, Customer Success", languageRequirement: "English (Native)",
          toolsRequired: "Google Docs, Notion", portfolioExpectation: "SaaS case studies",
          turnaroundTime: "5 business days", replacementRisk: "High",
        },
        {
          id: "li-4", creatorTypes: ["Designer"], numberOfCreators: 1, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Assignment", estimatedMonthlyOutput: "15 designs", estimatedHoursPerMonth: "60",
          clientPay: 140000, creatorPay: 82500, isCombinedPay: false, targetMarginPercent: 40,
          grossMargin: 57500, grossMarginPercent: 41.1,
          domainExpertise: "SaaS, Enterprise", languageRequirement: "English",
          toolsRequired: "Figma, Illustrator", portfolioExpectation: "B2B SaaS design portfolio",
          turnaroundTime: "3 business days", replacementRisk: "Medium",
        },
      ],
      requiredStartDate: "2026-02-15",
      deadlineToClose: "2026-02-10",
      urgency: "low",
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "Closed – Filled",
    headOfSupplyNotes: "Good deal. Approved.",
    rejectionReason: "",
    taManagerAssigned: "Neha Gupta",
    recruiterAssigned: "Neha Gupta",
    linkedInRecruiterLink: "https://www.linkedin.com/recruiter/projects/67890",
    targetClosureDate: "2026-02-10",
    createdAt: "2026-01-05T11:00:00Z",
    updatedAt: "2026-02-10T16:00:00Z",
    totalClientRevenue: 315000,
    totalCreatorCost: 187500,
    grossMargin: 127500,
    grossMarginPercent: 40.5,
    targetMarginPercent: 40,
    dailyUpdates: [],
    auditLog: [],
  },
  {
    id: "AREQ-004",
    raisedByName: "Priya Sharma",
    raisedByPhone: "+91 98765 43210",
    department: "VSD",
    flow: "vsd",
    salesData: undefined,
    vsdData: {
      clientName: "Zerodha",
      dealId: "DEAL-004",
      dealType: "Retainer",
      studioType: "Hybrid",
      geography: "India",
      opportunityStage: "SLA back-and-forth",
      clientDetails: "Leading discount brokerage. Scale: Large volume of educational content. Expectations: SEBI-compliant, investor-friendly. Complexity: Regulatory constraints.",
      lineItems: [
        {
          id: "li-5", creatorTypes: ["Writer"], numberOfCreators: 4, experienceLevel: "Senior (5–8 yrs)",
          paymentModel: "Per Word", estimatedMonthlyOutput: "60,000 words", estimatedHoursPerMonth: "",
          clientPay: 280000, creatorPay: 168000, isCombinedPay: false, targetMarginPercent: 45,
          grossMargin: 112000, grossMarginPercent: 40,
          domainExpertise: "Finance, Investments", languageRequirement: "English, Hindi",
          toolsRequired: "Google Docs", portfolioExpectation: "Finance writing samples",
          turnaroundTime: "72 hours", replacementRisk: "High",
        },
      ],
      requiredStartDate: "2026-03-01",
      deadlineToClose: "2026-03-15",
      urgency: "medium",
      isReplacementHiring: false,
      replacementOf: "",
    },
    status: "Approved – Assigning",
    headOfSupplyNotes: "Margin below target at line level. Need to renegotiate writer pay or increase client billing.",
    rejectionReason: "",
    taManagerAssigned: "",
    recruiterAssigned: "",
    linkedInRecruiterLink: "",
    targetClosureDate: "",
    createdAt: "2026-02-05T08:00:00Z",
    updatedAt: "2026-02-23T10:00:00Z",
    totalClientRevenue: 280000,
    totalCreatorCost: 168000,
    grossMargin: 112000,
    grossMarginPercent: 40,
    targetMarginPercent: 45,
    dailyUpdates: [],
    auditLog: [
      { id: "a-2", fieldChanged: "status", oldValue: "Pending Head of Supply Review", newValue: "Approved – Assigning", editedBy: "Head of Supply", timestamp: "2026-02-23T10:00:00Z" },
    ],
  },
];
